-- MySQL Script generated by MySQL Workbench
-- Wed Oct 30 10:26:39 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Rr5s8PgcAw
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Rr5s8PgcAw
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Rr5s8PgcAw` DEFAULT CHARACTER SET utf8 ;
USE `Rr5s8PgcAw` ;

-- -----------------------------------------------------
-- Table `Rr5s8PgcAw`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rr5s8PgcAw`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `birthday` DATE NULL,
  `identity` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `email` VARCHAR(255) NULL,
  `address` VARCHAR(1000) NULL,
  `sex` VARCHAR(45) NULL,
  `facebook` VARCHAR(500) NULL,
  `zalo` VARCHAR(500) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `phone_UNIQUE` (`phone` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `identity_UNIQUE` (`identity` ASC) VISIBLE);


-- -----------------------------------------------------
-- Table `Rr5s8PgcAw`.`employees`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rr5s8PgcAw`.`employees` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `position` INT NULL,
  `datejoined` DATE NULL,
  `userid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_employees_useridx` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_employees_user`
    FOREIGN KEY (`userid`)
    REFERENCES `Rr5s8PgcAw`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `Rr5s8PgcAw`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Rr5s8PgcAw`.`customers` (
  `id` INT NOT NULL,
  `type` INT NULL COMMENT 'Loại khách hàng',
  `lastpurchase` DATE NULL COMMENT 'Lần mua cuối',
  `total` DOUBLE NULL COMMENT 'Tổng tiền hàng',
  `debt` DOUBLE NULL COMMENT 'Tiền nợ',
  `userid` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_customers_user1_idx` (`userid` ASC) VISIBLE,
  CONSTRAINT `fk_customers_user1`
    FOREIGN KEY (`userid`)
    REFERENCES `Rr5s8PgcAw`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
